import { Icon } from '@/components/Button/button.styles'
import { loginWithGitHub, onAuthStateChanged } from '@/firebase/client'
import { AppLayout, Button } from '@/components'
import { ContainerSection, SubTitle, Title } from './home.styles'
import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

interface User {
  avatar: string;
  username: string;
  name: string;
  email: string;
}

export default function Home() {

  const [user, setUser] = useState<User | undefined>(undefined);

  useEffect (() => {
    onAuthStateChanged(setUser)
  }, [])

  const handleClick = async () => {
    try {
      const user = await loginWithGitHub(); 
      const { avatar, username, name, email } = user;
      setUser(user);
      console.log(user);
    } catch (err) {
      console.log(err);
    }
  };

  return (
    <>
      <Head>
        <title>devter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
        <ContainerSection>
          <Image 
            src="/devter1.svg" 
            alt="Logo" 
            width={100}
            height={100}
          />
          <Title>Devter</Title>
          <SubTitle>Talk about development with developers 👩‍💻👨‍💻</SubTitle> 
          {
            user === null && 
              <Button onClick={handleClick}>
                <Icon size={25} fill="#fff" />
                Login with GitHub
              </Button>
          }
          {
            user && user.avatar &&
              <div>
                <img src={user.avatar} alt={user.username} />
                <strong>{user.username}</strong>
              </div>
          }
              
        </ContainerSection>
      </AppLayout>
    </>
  )
}
